name: Test

on: 
  push:
    branches: '**'

jobs:
  test:
    runs-on: macos-12
    steps:
    - name: Installing Docker
      run: brew install docker colima
    - name: Testing folders with spaces
      run: |
        mkdir "folder with spaces"
        cd "folder with spaces"
        echo $(pwd)
        ls -l /usr/local/bin/docker*
        docker run --rm -v $(pwd):/home -w /home m365pnp/powershell pwsh Get-Module -ListAvailable
