name: Test

on: 
  push:
    branches: '**'

jobs:
  test:
    runs-on: macos-12
    steps:
    - name: Installing Docker
      run: brew install --cask docker
    - name: Testing folders with spaces
      run: |
        mkdir "folder with spaces"
        cd "folder with spaces"
        echo $(pwd)
        docker -v
