name: Test

on: 
  push:
    branches: '**'

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - name: Testing folders with spaces
      run: |
        echo $(pwd)
        docker run --rm -v $(pwd):/home -w /home m365pnp/powershell pwsh Get-Module -ListAvailable
